// settings.js
// credit by Kevin tech 

const config = require('./setting/config');


const settings = {
  SESSION_ID: config.SESSION_ID || "", //starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZUl3WEFaWENPK0VSS1JyaWN2UzJIbHRsVThxWjNJejJJaG1oRjQzdlhGbz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiM2dTbWcxTi9rcmtsZTJ6N01rNGxybzhGL2xOQ0lVVDZUbmhwNUd2VGhudz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJrTzRiWDErL2VMcWNsQ1pKTE5uUi9TaW5VU0g4QklpaDRxSzJua0FCREZVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJIYytrY3JmUWwrOFRhMWJjeXBoaGtTSlpkZmwyWCs3MENJZDNkelJ2ZVRJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImNKOXV4blp5Qkw3dWxTclpmc2trT0NzMXJldzNlR3FkV0RtRDlZN1BPa1U9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJRbUxLa3BHM2VkS0FkYnN5TGZxVjA4VkNEY25HRXhUVGZ5alpMZmU4elE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiVVBnT2Zna1I2Si9UbWs0dWR5U20zMUsySVNvL2kydDVwbzkwNkJ1WWhGUT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ3F5U21VNFl3NTR4OFJSY0FoZmpXSXNxdFZwcVNPT21GeUE0bGRjVnUwUT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlpmUFd3YXJnQ3dSelN5MTE1RFN6OEFrUGhJSWFqd2dvZGI2aG9HUGNCa1NOcHNFTzVNN3NzUGFJNFRjcVZnMXcybG5ieWs4Um5RSzZ1UmlLL2UwdEJBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTM4LCJhZHZTZWNyZXRLZXkiOiJVNk1JRmNhNFBuc0hMek1jTUNTUUh5UVZIb1VPWDdTKytBbzZwRjBCNDNVPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJRNURHMVFCUSIsIm1lIjp7ImlkIjoiMjc2ODU3MDk2ODU6NzRAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiIxODE0NTAxMzc3MDY1MzQ6NzRAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNQdTNvZU1HRVAyczRzWUdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJsUjlmbkJZSGRlamdtMzVMdnUzUWRIRyswZ1ZrWlJ0M3Nsd3JaeGVWTDFBPSIsImFjY291bnRTaWduYXR1cmUiOiJoV0pjbXJYSVFFcTQ2YW9iTWdidlVjTTlxems2aWNJUEJWa3o2Y1JiVkdDR01IZGFjc3lQZXpQbi8rZzdSNjlNNnlWZUh6RVJoLzl3S2lwcHd1ZFNEUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiKzNySk5OYzlVeTBJN3liY3FXdGZWTXF1WWlGb24zVkhiaytpZjdrazdhbUlOZksvRDJPcjQwUUx2a3UxWUJ6THd2bFl2Zno4bktDcDJ2RE5SSTUvQVE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNzY4NTcwOTY4NTo3NEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJaVWZYNXdXQjNYbzRKdCtTNzd0MEhSeHZ0SUZaR1ViZDdKY0syY1hsUzlRIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQTBJRWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTkwMjQ3NzksImxhc3RQcm9wSGFzaCI6IjJWNzdxVSJ9 enter session id
  ownername: config.ownername || "ᴋᴇʟᴠɪɴ ᴛᴇᴄʜ", // Owner name
  botname: config.botname || "ᴠɪɴɪᴄ xᴍᴅ", // cvimcustom bot name
  prefa: config.prefa || ['.', '!'], // Command prefixes
  owner: config.owner || ["27685709685"] // 27685709685
};

// Export settings for use in other modules
module.exports = settings;

// Watch for changes to this file and reload if updated
const fs = require('fs');
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log('\x1b[0;32m' + __filename + ' \x1b[1;32mupdated!\x1b[0m');
  delete require.cache[file];
  require(file);
});
